language: rust
sudo: false
cache: cargo

addons:
  apt:
    update: true
    packages:
      - valgrind

env:
  - RUST_BACKTRACE=full

script:
  - cargo build --all --verbose
  - cargo test --all --verbose
  - cargo test --all --verbose --all-features
  # Run test with feature flags in subdir as cargo does not support feature
  # flags in virtual workspace
  - cd libsignal-protocol
  - cargo test --all --verbose --no-default-features --features="crypto-openssl"
  - cargo test --all --verbose --no-default-features --features="crypto-native"
  - cd ..
  - cargo doc --all --verbose
    # Check that the (non-blacklisted) examples and tests don't have memory bugs
  - python3 ./scripts/valgrind.py

before_deploy:
  - cargo doc --all --verbose
  - echo '<meta http-equiv="refresh" content="0; url=libsignal_protocol/index.html" /> ' > target/doc/index.html
  - cp -r target/doc public

matrix:
  fast_finish: true
  # Uncomment the following lines whenever clippy fails to install on nightly
  allow_failures:
   - name: "Code Style"

  include:
    - rust: stable
    # ptr_cast requires rustc 1.38.0
    # there's a failure when documenting the subtle crate with 1.38.0
    - rust: 1.42.0
    - rust: nightly

    - rust: nightly
      name: "Code Style"
      before_script:
        - rustup component add rustfmt
        - rustup component add clippy
      script:
        - cargo fmt --all -- --check
        - cargo clippy -- -D clippy::all

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  local_dir: public
  on:
    branch: master
    # nightly gives us better docs (intra-doc links)
    condition: "$TRAVIS_RUST_VERSION == nightly"
